// Cloudflare needs to see the FlareTraceAgent class exported from the Worker
// entry point so it can instantiate the Durable Object.
export { FlareTraceAgent } from './agent';

import { getAgentByName } from 'agents';
import { FlareTraceAgent } from './agent';

// Env is generated by `wrangler types` into worker-configuration.d.ts.
// After adding the Durable Object binding it now includes:
//   AI: Ai
//   ASSETS: Fetcher
//   FLARETRACE_AGENT: DurableObjectNamespace<FlareTraceAgent>

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname.startsWith('/api/')) {
      return handleApi(request, env, url);
    }

    return env.ASSETS.fetch(request);
  },
} satisfies ExportedHandler<Env>;

async function handleApi(request: Request, env: Env, url: URL): Promise<Response> {
  if (url.pathname === '/api/chat'    && request.method === 'POST') return handleChat(request, env);
  if (url.pathname === '/api/history' && request.method === 'GET')  return handleHistory(request, env, url);
  if (url.pathname === '/api/summary' && request.method === 'POST') return handleSummary(request, env);
  return json({ error: 'Not found' }, 404);
}

async function handleChat(request: Request, env: Env): Promise<Response> {
  // Clone the body before reading it - we need to inspect sessionId here
  // before forwarding just the message to the Agent.
  let body: { message?: string; sessionId?: string };
  try {
    body = await request.json();
  } catch {
    return json({ error: 'Invalid JSON body.' }, 400);
  }

  const message = body.message?.trim();
  if (!message) {
    return json({ error: 'message is required.' }, 400);
  }

  const sessionId = body.sessionId?.trim();
  if (!sessionId) {
    return json({ error: 'sessionId is required.' }, 400);
  }

  // getAgentByName is the Agents SDK function that:
  //   1. Derives a stable Durable Object ID from the sessionId string
  //   2. Gets (or creates) the FlareTraceAgent instance for that ID
  //   3. Returns a stub we can .fetch() to invoke the Agent's onRequest()
  //
  // Different sessionIds → different Durable Object instances → isolated state.
  // The same sessionId always routes to the same instance → persistent memory.
  const agent = await getAgentByName(env.FLARETRACE_AGENT, sessionId);

  // Forward the message to the Agent via HTTP.
  // The Agent's onRequest() handler takes over from here.
  return agent.fetch(
    new Request('https://agent/chat', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ message }),
    })
  );
}

async function handleHistory(_request: Request, env: Env, url: URL): Promise<Response> {
  const sessionId = url.searchParams.get('sessionId')?.trim();
  if (!sessionId) return json({ error: 'sessionId is required.' }, 400);
  const agent = await getAgentByName(env.FLARETRACE_AGENT, sessionId);
  return agent.fetch(new Request('https://agent/history', { method: 'GET' }));
}

async function handleSummary(request: Request, env: Env): Promise<Response> {
  let body: { sessionId?: string };
  try { body = await request.json(); } catch { return json({ error: 'Invalid JSON body.' }, 400); }
  const sessionId = body.sessionId?.trim();
  if (!sessionId) return json({ error: 'sessionId is required.' }, 400);
  const agent = await getAgentByName(env.FLARETRACE_AGENT, sessionId);
  return agent.fetch(new Request('https://agent/summary', { method: 'POST' }));
}

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}
